### ISSUE TITLE
Chinese charset exception when reading dataset

### ISSUE THREAD

**Issue by zyy13579** [nroduit/Weasis#119]
when load ct film,weasis will crashed。
I find the reason is LoadSeries.java  at line 490
weasis-dicom/weasis-dicom-explorer/src/main/java/org/weasis/dicom/explorer/wado/LoadSeries.java

thumURL = (String) dicomSeries.getTagValue(TagW.DirectDownloadThumbnail);
                if (StringUtil.hasLength(thumURL)) {
                    if (thumURL.startsWith(Thumbnail.THUMBNAIL_CACHE_DIR.getPath())) {
                        file = new File(thumURL);
                        thumURL = null;
                    } else {
                        thumURL = wadoParameters.getBaseURL() + thumURL;
                        extension = FileUtil.getExtension(thumURL);
                    }
                }

the thumURL is possible will be null ,so when execute StringUtil.hasLength(thumURL) ,program will crashed,  add thumURL!=null before StringUtil.hasLength(thumURL)  will fixed this problem

**Comment by nroduit** [comment]
No, StringUtil.hasLength(thumURL) support null value.

Please provide [logs](https://nroduit.github.io/en/faq/#how-to-enable-weasis-logging) or a sample.

**Comment by zyy13579** [comment]
$dicom:get -w https://dicom.tongxinyiliao.com/xml/20200316/200316024001.xml
You are right,when I use eclipse run code at 3.6.0,it is no problem,can show all film
but when I use the release weasis 3.6.0 open the same ct film, 
at begin I have 4 thumbnail position in left（no picture show）,
and then it will disappear one by one(loading film),
until nothing in left thumbnail list.

**Comment by zyy13579** [comment]
➜  ~ cat .weasis/log/boot-0.log
18.03.2020 13:10:32.665 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
18.03.2020 13:10:32.769 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
18.03.2020 13:10:32.769 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = weasis://%24dicom%3Aget%20-w%20https%3A%2F%2Fdicom.tongxinyiliao.com%2Fxml%2F20200316%2F200316024001.xml
18.03.2020 13:10:32.852 *CONFIG* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 49,866
18.03.2020 13:10:32.862 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
18.03.2020 13:10:32.862 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
18.03.2020 13:10:32.862 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
18.03.2020 13:10:32.862 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
18.03.2020 13:10:32.863 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
18.03.2020 13:10:32.863 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
18.03.2020 13:10:32.863 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
18.03.2020 13:10:32.863 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
18.03.2020 13:10:34.403 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
18.03.2020 13:10:34.403 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
18.03.2020 13:10:34.417 *INFO* [main] org.weasis.launcher.WeasisLauncher:
***** Configuration *****
  Last running version = null
  Current version = 3.6.0
  Application name = Weasis
  Application Source ID = 419B40DE
  Application Profile = default
  Application local codebase = /Applications/Weasis.app/Contents/app
  Application codebase URL = file:/Applications/Weasis.app/Contents/app
  Application configuration file = file:/Applications/Weasis.app/Contents/app/conf/config.properties
  Application extension configuration file = file:/Applications/Weasis.app/Contents/app/conf/ext-config.properties
  User = zyy
  User home directory = /Users/zyy/.weasis
  Resources path = /Applications/Weasis.app/Contents/app/resources
  Preferences directory = /Users/zyy/.weasis/preferences/zyy/default
  Look and Feel = com.apple.laf.AquaLookAndFeel
  Languages path = file:/Applications/Weasis.app/Contents/app/bundle-i18n/
  Languages available = en,ar,az_AZ,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,ka,de,el,hu_HU,it,ja,ko,ms_MY,fa,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = macosx-x86-64
  HTTP user agent = Weasis/3.6.0 (Mac OS X; 10.15.3; x86_64)
  Operating system = Mac OS X 10.15.3 x86_64
  Java vendor = N/A
  Java version = 15-internal
  Java Path = /Applications/Weasis.app/Contents/runtime/Contents/Home
  Java max memory (less survivor space) = 4.0 GiB
***** End of Configuration *****
18.03.2020 13:10:34.420 *INFO* [main] org.weasis.launcher.WeasisLauncher:
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

18.03.2020 13:10:37.567 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.

**Comment by nroduit** [comment]
If you are talking about an unpredictable crash on the latest OS X system, see https://github.com/nroduit/Weasis/issues/116

**Comment by zyy13579** [comment]
windows have same problem

18.03.2020 16:54:26.677 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
18.03.2020 16:54:26.841 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
18.03.2020 16:54:26.842 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = C:\Users\unimed\Desktop\影像相关\Xia_Gang_Hui\1-1_1_00003EA5.DCM
18.03.2020 16:54:26.930 *CONFIG* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 51,651
18.03.2020 16:54:27.507 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
18.03.2020 16:54:27.508 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
18.03.2020 16:54:27.510 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
18.03.2020 16:54:27.514 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
18.03.2020 16:54:27.516 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
18.03.2020 16:54:27.517 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
18.03.2020 16:54:27.518 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
18.03.2020 16:54:27.519 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
18.03.2020 16:54:29.285 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
18.03.2020 16:54:29.287 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
18.03.2020 16:54:29.384 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = null
  Current version = 3.6.0
  Application name = Gewu
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/config.properties
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties
  User = unimed
  User home directory = C:\Users\unimed\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\unimed\.weasis\preferences\unimed\default
  Look and Feel = org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = en,ar,az_AZ,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,ka,de,el,hu_HU,it,ja,ko,ms_MY,fa,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = windows-x86-64
  HTTP user agent = Gewu/3.6.0 (Windows 10; 10.0; amd64)
  Operating system = Windows 10 10.0 amd64
  Java vendor = Oracle Corporation
  Java version = 14
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 2.0 GiB
***** End of Configuration *****
18.03.2020 16:54:29.394 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

18.03.2020 16:54:36.215 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
18.03.2020 16:54:41.051 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Execute command
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.weasis.launcher.WeasisLauncher.commandSessionExecute(WeasisLauncher.java:637)
	at org.weasis.launcher.WeasisLauncher.lambda$executeCommands$1(WeasisLauncher.java:377)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.apache.felix.gogo.runtime.SyntaxError: bad unicode
	at org.apache.felix.gogo.runtime.BaseTokenizer.escape(BaseTokenizer.java:115)
	at org.apache.felix.gogo.runtime.BaseTokenizer.skipQuote(BaseTokenizer.java:153)
	at org.apache.felix.gogo.runtime.Tokenizer.next(Tokenizer.java:191)
	at org.apache.felix.gogo.runtime.Parser.next(Parser.java:283)
	at org.apache.felix.gogo.runtime.Parser.statement(Parser.java:320)
	at org.apache.felix.gogo.runtime.Parser.program(Parser.java:228)
	at org.apache.felix.gogo.runtime.Closure.<init>(Closure.java:84)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:178)
	... 19 more
18.03.2020 16:54:41.262 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Execute command
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:564)
	at org.weasis.launcher.WeasisLauncher.commandSessionExecute(WeasisLauncher.java:637)
	at org.weasis.launcher.WeasisLauncher.lambda$executeCommands$1(WeasisLauncher.java:377)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:312)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at java.desktop/javax.swing.JOptionPane.showOptionDialog(JOptionPane.java:874)
	at org.weasis.launcher.WeasisLauncher.lambda$showMessage$2(WeasisLauncher.java:410)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:316)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:770)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:391)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:740)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: org.apache.felix.gogo.runtime.SyntaxError: bad unicode
	at org.apache.felix.gogo.runtime.BaseTokenizer.escape(BaseTokenizer.java:115)
	at org.apache.felix.gogo.runtime.BaseTokenizer.skipQuote(BaseTokenizer.java:153)
	at org.apache.felix.gogo.runtime.Tokenizer.next(Tokenizer.java:191)
	at org.apache.felix.gogo.runtime.Parser.next(Parser.java:283)
	at org.apache.felix.gogo.runtime.Parser.statement(Parser.java:320)
	at org.apache.felix.gogo.runtime.Parser.program(Parser.java:228)
	at org.apache.felix.gogo.runtime.Closure.<init>(Closure.java:84)
	at org.apache.felix.gogo.runtime.CommandSessionImpl.execute(CommandSessionImpl.java:178)
	... 37 more
18.03.2020 16:55:58.844 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
18.03.2020 16:55:58.976 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
18.03.2020 16:55:58.978 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = weasis://%24dicom%3Aget%20-w%20https%3A%2F%2Fdicom.tongxinyiliao.com%2Fxml%2F20200316%2F200316024001.xml/
18.03.2020 16:55:59.063 *CONFIG* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 51,744
18.03.2020 16:55:59.349 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
18.03.2020 16:55:59.350 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
18.03.2020 16:55:59.350 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
18.03.2020 16:55:59.351 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
18.03.2020 16:55:59.353 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
18.03.2020 16:55:59.354 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
18.03.2020 16:55:59.354 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
18.03.2020 16:55:59.355 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
18.03.2020 16:56:01.221 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
18.03.2020 16:56:01.224 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
18.03.2020 16:56:01.259 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 3.6.0
  Current version = 3.6.0
  Application name = Gewu
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/config.properties
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/ext-config.properties
  User = unimed
  User home directory = C:\Users\unimed\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\unimed\.weasis\preferences\unimed\default
  Look and Feel = org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = en,ar,az_AZ,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,ka,de,el,hu_HU,it,ja,ko,ms_MY,fa,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = windows-x86-64
  HTTP user agent = Gewu/3.6.0 (Windows 10; 10.0; amd64)
  Operating system = Windows 10 10.0 amd64
  Java vendor = Oracle Corporation
  Java version = 14
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 2.0 GiB
***** End of Configuration *****
18.03.2020 16:56:01.270 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

18.03.2020 16:56:02.970 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.

**Comment by zyy13579** [comment]
[video](https://www.youtube.com/watch?v=Xj9HR_jZy1Q)

**Comment by nroduit** [comment]
I've tried on Linux without any issue.

On Windows the error is not caught (so that's why there is nothing in log). This issue comes from the dcm4che library which throws in java.lang.StringCoding.decode(charsetName, bytes, offset, length): java.io.UnsupportedEncodingException: GB18030

The embedded Java in Weasis not a minimal version, it is possible an additional module is required on Windows for the charset GB18030.

**Comment by nroduit** [comment]
I found that the extension charsets module is missing in the native build.
