### ISSUE TITLE
Error - unresolved requirements in a locally installed Weasis v3.6.0

### ISSUE THREAD

**Issue by arvgord** [nroduit/Weasis#127]
**Describe the bug**
Can't add [weasis-chcapi-extension
](https://github.com/GoogleCloudPlatform/weasis-chcapi-extension) to a locally installed Weasis on Ubuntu. I got:
```
ERROR: Bundle weasis-chcapi-extension [32] Error starting file:/opt/weasis/lib/app/plugins/weasis-chcapi-extension-3.0.7.jar (org.osgi.framework.BundleException: Unable to resolve weasis-chcapi-extension [32](R 32.0): missing requirement [weasis-chcapi-extension [32](R 32.0)] osgi.wiring.package; (osgi.wiring.package=javax.naming) Unresolved requirements: [[weasis-chcapi-extension [32](R 32.0)] osgi.wiring.package; (osgi.wiring.package=javax.naming)])
org.osgi.framework.BundleException: Unable to resolve weasis-chcapi-extension [32](R 32.0): missing requirement [weasis-chcapi-extension [32](R 32.0)] osgi.wiring.package; (osgi.wiring.package=javax.naming) Unresolved requirements: [[weasis-chcapi-extension [32](R 32.0)] osgi.wiring.package; (osgi.wiring.package=javax.naming)]
	at org.apache.felix.framework.Felix.resolveBundleRevision(Felix.java:4368)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2281)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1539)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:308)
	at java.base/java.lang.Thread.run(Thread.java:832)
```
But the v3.0.7 extension works with Weasis v3.6.0 portable.

**To Reproduce**
1. Create plugins folder in /opt/weasis/lib/app
2. Add weasis-chcapi-extension to plugins folder
3. Add the following preference to /opt/weasis/lib/app/conf/ext-config.properties:
```
felix.auto.start.85=${weasis.codebase.url}/plugins/weasis-chcapi-extension-3.0.7.jar
```
4. Run Weasis in console
4. See error described above

**Desktop:**
 - Ubuntu 20.04
 - Java Rutime: openjdk version "14.0.1"
 - Weasis Version v3.6.0
 - weasis-chcapi-extension - v3.0.7

**Comment by arvgord** [comment]
I'm closing this issue due to https://github.com/GoogleCloudPlatform/weasis-chcapi-extension/pull/39.
