### ISSUE TITLE
Dicom Explorer not showing thumbnails

### ISSUE THREAD

**Issue by kundanashish** [nroduit/Weasis#145]
Hi

When loading Weasis through WADO URL without server like below

weasis://$dicom:get -w https://dicomfilesprod.graticare.com/16/30072020/1.3.12.2.1107.5.1.4.80719.30000020072604352254600001007/8A0DCE1A727EE2DAA7291B2EF135EE5E.xml

It works fine when only single study is loaded. But when multiple studies are loaded, then the thumbnails are not shown.

Please help

**Comment by nroduit** [comment]
The manifest generated is not consistent because StudyInstanceUID does not match to the one in the DICOM file (it is the patient name). The UIDs in the manifest must match to the one in DICOM.

The manifest does not validate the XLS shema: see https://nroduit.github.io/en/basics/customize/integration/#build-your-own-connector
`06.08.2020 22:31:27.986 *ERROR* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.wado.DownloadManager: [Validate with XSD schema] wado_query is NOT valid org.xml.sax.SAXException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 335; cvc-complex-type.3.2.2: Attribute 'wadoURL' is not allowed to appear in element 'arcQuery'.
javax.xml.transform.TransformerException: javax.xml.stream.XMLStreamException: org.xml.sax.SAXParseException; lineNumber: 1; columnNumber: 335; cvc-complex-type.3.2.2: Attribute 'wadoURL' is not allowed to appear in element 'arcQuery'.
	at com.sun.org.apache.xerces.internal.jaxp.validation.StAXValidatorHelper.validate(StAXValidatorHelper.java:111)
	at com.sun.org.apache.xerces.internal.jaxp.validation.ValidatorImpl.validate(ValidatorImpl.java:123)`

**Comment by kundanashish** [comment]
Hu Nicolas

Thanks for quick response.

I will check and fix it.

I need a favor from you. We want to make some minor custom changes in
Weasis i.e adding a button that will redirect to our website where the url
will come for the XML link file attribute.

I am a web developer but don't know about windows application, so need to
hire a developer to do it.
Will you be able to do it or refer any developer for the work.
It will be a great help.

Thanks.

**Comment by nroduit** [comment]
Hi,

No, I have absolutely no availability for work mandates.

Ideally, you wouldn't have to modify the Weasis code for specific needs,
but rather make a plugin
<https://nroduit.github.io/en/basics/customize/build-plugins/>. There's
just an example of how to add a button in the toolbar.

Best,

Nicolas

Le ven. 7 août 2020 à 18:22, kundanashish <notifications@github.com> a
écrit :

**Comment by kundanashish** [comment]
Hi Nicolas

Bro I am in serious need of this.
I am an IT manager, in the hospital and the management desperately wants
this feature.

Even using several methods like Upwork and my contacts I am not able to
develop this.
I need to have this implemented even if the money goes from my pocket.
Please spare some of your valuable time for me.

You can only save me now. I can pay you for this to save my job. At
least give me the contact of a person who can help me.

Please help 🙏

**Comment by nroduit** [comment]
Unfortunately, my current activities do not allow me to respond to this kind of requests.

As I already told you, try to refer to [the examples of plugins](https://nroduit.github.io/en/basics/customize/build-plugins/) where there is just an example of a button added in the toolbar.
