### ISSUE TITLE
NoClassDefFoundError: org/apache/felix/framework/util/Util

### ISSUE THREAD

**Issue by Ligandfas** [nroduit/Weasis#162]
Hi ,
I am facing this exception when trying to compile weasis in Intellij:

Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/felix/framework/util/Util
	at org.weasis.launcher.ConfigData.filterConfigProperties(ConfigData.java:209)
	at org.weasis.launcher.ConfigData.initWeasisProperties(ConfigData.java:187)
	at org.weasis.launcher.ConfigData.init(ConfigData.java:128)
	at org.weasis.launcher.ConfigData.<init>(ConfigData.java:87)
	at org.weasis.launcher.WeasisLauncher.main(WeasisLauncher.java:185)
Caused by: java.lang.ClassNotFoundException: org.apache.felix.framework.util.Util
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:418)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:355)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:351)
	... 5 more

thank you

**Comment by nroduit** [comment]
If you are using the latest Intellij version, it is very tricky to find how to include the maven dependencies. I publish a [comment](https://youtrack.jetbrains.com/issue/IDEA-257364)

**Comment by Ligandfas** [comment]
thank you for the response, which version of intellij should work ok ?

**Comment by Ligandfas** [comment]
I just checked that am using intellij 2018

**Comment by Ligandfas** [comment]
Hi again just solved it with
