### ISSUE TITLE
IntelliJ java exec bug NoClassDefFoundError: org/apache/felix/framework/util/Util

### ISSUE THREAD

**Issue by jixiongwei** [nroduit/Weasis#177]
**Describe the bug**
Build all success but  run WeasisLauncher throws an error: `NoClassDefFoundError: org/apache/felix/framework/util/Util`

**Desktop (please complete the following information):**
 - OS: [Windows 10 x64]
 - Java Rutime: [OpenJDK Runtime Environment (build 15.0.2+7-27)]
 - Weasis Version [v3.7.0]

**Screenshots**
IntelliJ IDEA 2020.3.2 (Community Edition)
![image](https://user-images.githubusercontent.com/78500138/107848919-c25a9c80-6df7-11eb-9f5f-8e83d2de56d4.png)
Not like the [issue 162](https://github.com/nroduit/Weasis/issues/162)  , I have already checked the option `Include dependencies with "Provided" scope`

**Traces**
```
[INFO] 
[INFO] --- exec-maven-plugin:1.6.0:exec (default-cli) @ weasis-launcher ---
13.02.2021 12:28:01.762 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
13.02.2021 12:28:01.794 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/felix/framework/util/Util
	at org.weasis.launcher.ConfigData.filterConfigProperties(ConfigData.java:243)
	at org.weasis.launcher.ConfigData.initWeasisProperties(ConfigData.java:215)
	at org.weasis.launcher.ConfigData.init(ConfigData.java:142)
	at org.weasis.launcher.ConfigData.<init>(ConfigData.java:86)
	at org.weasis.launcher.WeasisLauncher.main(WeasisLauncher.java:183)
Caused by: java.lang.ClassNotFoundException: org.apache.felix.framework.util.Util
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 5 more
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
    at org.apache.commons.exec.DefaultExecutor.executeInternal (DefaultExecutor.java:404)
    at org.apache.commons.exec.DefaultExecutor.execute (DefaultExecutor.java:166)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:804)
    at org.codehaus.mojo.exec.ExecMojo.executeCommandLine (ExecMojo.java:751)
    at org.codehaus.mojo.exec.ExecMojo.execute (ExecMojo.java:313)
    at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (DefaultBuildPluginManager.java:137)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:210)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:156)
    at org.apache.maven.lifecycle.internal.MojoExecutor.execute (MojoExecutor.java:148)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:117)
    at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (LifecycleModuleBuilder.java:81)
    at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (SingleThreadedBuilder.java:56)
    at org.apache.maven.lifecycle.internal.LifecycleStarter.execute (LifecycleStarter.java:128)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:305)
    at org.apache.maven.DefaultMaven.doExecute (DefaultMaven.java:192)
    at org.apache.maven.DefaultMaven.execute (DefaultMaven.java:105)
    at org.apache.maven.cli.MavenCli.execute (MavenCli.java:957)
    at org.apache.maven.cli.MavenCli.doMain (MavenCli.java:289)
    at org.apache.maven.cli.MavenCli.main (MavenCli.java:193)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (Native Method)
    at jdk.internal.reflect.NativeMethodAccessorImpl.invoke (NativeMethodAccessorImpl.java:64)
    at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke (Method.java:564)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (Launcher.java:282)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch (Launcher.java:225)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (Launcher.java:406)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main (Launcher.java:347)
    at org.codehaus.classworlds.Launcher.main (Launcher.java:47)
```

**Update**
Temporary workaround: add felix.jar to the -classpath to the commandline.

**Comment by nroduit** [comment]
This is strange because it is exactly the error when  **Include dependencies with "Provided" scope** is not activated.

Try to change the working directory in weasis-launcher:
![Sélection_061](https://user-images.githubusercontent.com/993975/108080463-2f786700-7070-11eb-85e0-0b2411d449d2.png)

**Comment by jixiongwei** [comment]
Hello Nicolas,
	Thanks for your reply. It is working now: nothing was done except adding the felix.jar to the java option. What is strange is with the same arguments, it was not working. Maybe a cache issue.
