### ISSUE TITLE
Some studies are appearing blank after selecting from explorer

### ISSUE THREAD

**Issue by PriyankaWasnik** [nroduit/Weasis#261]
There are two issues i'm encountering in this viewer:-
1. Some images are not getting render after selecting them from explorer.(screenshot-1)
2. Once I zoom in/out on those empty window then they just come up with some other black window over them..(screenshot-2)

**Desktop**
 - OS: - Windows 7
 - Java Rutime: 1.8.0_121-b13
 - Weasis Version : 2.0.4

**Screenshots**
![1stImage](https://user-images.githubusercontent.com/83577592/165955916-b66a8b55-ad3d-47e6-94fd-a77561b8bf1b.png)
![2ndImage](https://user-images.githubusercontent.com/83577592/165955964-f889732a-36c6-4bda-8525-f5bbe61814da.png)

**Traces**
*ERROR* [AWT-EventQueue-2] org.weasis.core.api.internal.Activator: JAI Error in com.sun.media.jai.util.SunTileScheduler@5c144e: Problem occurs when computing a tile by the owner. java.lang.ArrayIndexOutOfBoundsException: -1
	at javax.media.jai.LookupTableJAI.lookupU(Unknown Source)
	at javax.media.jai.LookupTableJAI.lookup(Unknown Source)
	at com.sun.media.jai.opimage.LookupOpImage.computeRect(Unknown Source)
	at javax.media.jai.PointOpImage.computeTile(Unknown Source)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(Unknown Source)
	at javax.media.jai.OpImage.getTile(Unknown Source)
	at javax.media.jai.PlanarImage.getData(Unknown Source)
	at javax.media.jai.PlanarImage.getExtendedData(Unknown Source)
	at javax.media.jai.ScaleOpImage.computeTile(Unknown Source)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(Unknown Source)
	at javax.media.jai.OpImage.getTile(Unknown Source)
	at javax.media.jai.PlanarImage.getData(Unknown Source)
	at javax.media.jai.RenderedOp.getData(Unknown Source)
	at sun.java2d.SunGraphics2D.drawRenderedImage(Unknown Source)
	at org.weasis.core.ui.model.layer.imp.RenderedImageLayer.drawImage(RenderedImageLayer.java:230)
	at org.weasis.core.ui.editor.image.DefaultView2d.draw(DefaultView2d.java:899)
	at org.weasis.core.ui.editor.image.DefaultView2d.paintComponent(DefaultView2d.java:883)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
 *ERROR* [AWT-EventQueue-2] org.weasis.core.api.internal.Activator: JAI Error in com.sun.media.jai.util.SunTileScheduler@5c144e: Problem occurs when computing a tile by the owner. java.lang.NullPointerException
	at com.sun.media.jai.util.SunCachedTile.<init>(Unknown Source)
	at com.sun.media.jai.util.SunTileCache.add(Unknown Source)
	at javax.media.jai.OpImage.addTileToCache(Unknown Source)
	at javax.media.jai.OpImage.getTile(Unknown Source)
	at javax.media.jai.PlanarImage.getData(Unknown Source)
	at javax.media.jai.PlanarImage.getExtendedData(Unknown Source)
	at javax.media.jai.ScaleOpImage.computeTile(Unknown Source)
	at com.sun.media.jai.util.SunTileScheduler.scheduleTile(Unknown Source)
	at javax.media.jai.OpImage.getTile(Unknown Source)
	at javax.media.jai.PlanarImage.getData(Unknown Source)
	at javax.media.jai.RenderedOp.getData(Unknown Source)
	at sun.java2d.SunGraphics2D.drawRenderedImage(Unknown Source)
	at org.weasis.core.ui.model.layer.imp.RenderedImageLayer.drawImage(RenderedImageLayer.java:230)
	at org.weasis.core.ui.editor.image.DefaultView2d.draw(DefaultView2d.java:899)
	at org.weasis.core.ui.editor.image.DefaultView2d.paintComponent(DefaultView2d.java:883)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
 *ERROR* [AWT-EventQueue-2] org.weasis.core.ui.model.layer.imp.RenderedImageLayer: Draw rendered image java.lang.NullPointerException
	at javax.media.jai.PlanarImage.getData(Unknown Source)
	at javax.media.jai.RenderedOp.getData(Unknown Source)
	at sun.java2d.SunGraphics2D.drawRenderedImage(Unknown Source)
	at org.weasis.core.ui.model.layer.imp.RenderedImageLayer.drawImage(RenderedImageLayer.java:230)
	at org.weasis.core.ui.editor.image.DefaultView2d.draw(DefaultView2d.java:899)
	at org.weasis.core.ui.editor.image.DefaultView2d.paintComponent(DefaultView2d.java:883)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at bibliothek.gui.dock.util.BackgroundPanel.paintChildren(BackgroundPanel.java:155)
	at javax.swing.JComponent.paint(Unknown Source)
	at bibliothek.gui.dock.util.BackgroundPanel.paint(BackgroundPanel.java:105)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at bibliothek.gui.dock.util.BackgroundPanel.paintChildren(BackgroundPanel.java:155)
	at javax.swing.JComponent.paint(Unknown Source)
	at bibliothek.gui.dock.util.BackgroundPanel.paint(BackgroundPanel.java:105)
	at javax.swing.JComponent.paintChildren(Unknown Source)

Pls help me out to overcome from this problem.

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
