### ISSUE TITLE
Error launching Weasis on Ubuntu

### ISSUE THREAD

**Issue by leonardorame** [nroduit/Weasis#412]
Hi, I'm getting this error on a new Ubuntu 20.04 machine:

Does anyone know if I there's a missing package?. I tried with Weasis 4.1.0 and 3.8.1 (this error is from the later).

```
(process:1161): GLib-GObject-WARNING **: 08:31:57.725: invalid (NULL) pointer instance

(process:1161): GLib-GObject-CRITICAL **: 08:31:57.781: g_signal_connect_data: assertion 'G_TYPE_CHECK_INSTANCE (instance)' failed
WARNING: package com.sun.awt not in java.desktop
15.05.2023 08:31:59.447 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
15.05.2023 08:31:59.697 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
15.05.2023 08:31:59.820 *CONFIG* [main] org.weasis.launcher.ConfigData: Properties: {weasis.export.dicom.send=true, weasis.user=root, weasis.name=Weasis, weasis.version=3.8.1, weasis.config.hash=1490119093, weasis.path=/root/.weasis, weasis.launch.type=NATIVE, weasis.import.dicom=true, weasis.codebase.url=file:/compat/ubuntu/opt/weasis/lib/app, weasis.pref.local.session=true, weasis.codebase.local=/compat/ubuntu/opt/weasis/lib/app, weasis.export.dicom=true, weasis.import.dicom.qr=true, felix.extended.config.properties=file:/compat/ubuntu/opt/weasis/lib/app/conf/ext-config.properties, felix.config.properties=file:/compat/ubuntu/opt/weasis/lib/app/conf/config.properties, weasis.source.id=D6AF4567, weasis.profile=default, http.agent=Weasis/3.8.1 (Linux; 3.17.0; amd64; default; NATIVE)}
15.05.2023 08:31:59.929 *CONFIG* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 19,832
15.05.2023 08:31:59.993 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
15.05.2023 08:31:59.994 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
15.05.2023 08:31:59.994 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
15.05.2023 08:31:59.994 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
15.05.2023 08:31:59.994 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
15.05.2023 08:31:59.994 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
15.05.2023 08:31:59.995 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
15.05.2023 08:31:59.995 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
15.05.2023 08:32:00.617 *CONFIG* [main] sun.awt.X11.backingStore.XToolkit: The system property sun.awt.backingStore is not set, by default backingStore=NotUseful
15.05.2023 08:32:01.782 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
15.05.2023 08:32:01.782 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
15.05.2023 08:32:01.785 *INFO* [main] org.weasis.launcher.WeasisLauncher:
***** Configuration *****
  Last running version = 3.8.1
  Current version = 3.8.1
  Application name = Weasis
  Application Source ID = D6AF4567
  Application Profile = default
  Application local codebase = /compat/ubuntu/opt/weasis/lib/app
  Application codebase URL = file:/compat/ubuntu/opt/weasis/lib/app
  Application configuration file = file:/compat/ubuntu/opt/weasis/lib/app/conf/config.properties
  Application extension configuration file = file:/compat/ubuntu/opt/weasis/lib/app/conf/ext-config.properties
  User = root
  User home directory = /root/.weasis
  Resources path = /compat/ubuntu/opt/weasis/lib/app/resources
  Preferences directory = /root/.weasis/preferences/root/default
  Look and Feel = org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel
  Languages path = file:/compat/ubuntu/opt/weasis/lib/app/bundle-i18n/
  Languages available = en,ar,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,de,el,hu_HU,it,ja,ko,ms_MY,fa,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,si,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = linux-x86-64
  HTTP user agent = Weasis/3.8.1 (Linux; 3.17.0; amd64; default; NATIVE)
  Operating system = Linux 3.17.0 amd64
  Java vendor = Eclipse Foundation
  Java version = 16.0.2
  Java Path = /compat/ubuntu/opt/weasis/lib/runtime
  Java max memory (less survivor space) = 1.9 GiB
***** End of Configuration *****
15.05.2023 08:32:01.806 *INFO* [main] org.weasis.launcher.WeasisLauncher:
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

15.05.2023 08:32:02.469 *INFO* [FelixStartLevel] org.apache.sling.commons.log.internal.LogManager: LogManager: Logging set up from context
15.05.2023 08:32:03.138 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
15.05.2023 08:32:03.138 *INFO* [FelixStartLevel] org.weasis.core.api.internal.cv.NativeOpenCVCodec: Native OpenCV is activated
15.05.2023 08:32:03.139 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: OpenCV imgcodecs
15.05.2023 08:32:03.489 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: JDK ImageIO
15.05.2023 08:32:03.555 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Activate DicomCodec
15.05.2023 08:32:03.561 *INFO* [FelixStartLevel] org.weasis.core.api.internal.Activator: Register Image Codec Plug-in: dcm4che
15.05.2023 08:32:04.342 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: Default System Application
15.05.2023 08:32:04.546 *ERROR* [FelixStartLevel] org.weasis.core.api.gui.util.GuiExecutor: EDT invokeAndWait() java.lang.reflect.InvocationTargetException
    at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
    at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
    at java.desktop/javax.swing.SwingUtilities.invokeAndWait(Unknown Source)
15.05.2023 08:32:04.565 *INFO* [FelixStartLevel] org.weasis.base.ui.gui.WeasisWinListener: Activate the main window PropertyChangeListener
15.05.2023 08:32:04.584 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: SR => org.weasis.dicom.sr.SRElementFactory
15.05.2023 08:32:04.838 *INFO* [AWT-EventQueue-0] org.weasis.base.ui.gui.WeasisWinListener: Register data explorer Plug-in: DICOM Explorer
15.05.2023 08:32:04.845 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: DICOM Structured Report
15.05.2023 08:32:04.960 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: 2D-DICOM Viewer
15.05.2023 08:32:04.973 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: ECG => org.weasis.dicom.wave.WaveElementFactory
15.05.2023 08:32:04.974 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: HD => org.weasis.dicom.wave.WaveElementFactory
15.05.2023 08:32:04.978 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: DICOM Waveform
15.05.2023 08:32:04.986 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: AU => org.weasis.dicom.au.AuElementFactory
15.05.2023 08:32:04.989 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: DICOM Voice Audio Waveform
15.05.2023 08:32:05.028 *INFO* [AWT-EventQueue-0] org.weasis.core.ui.internal.Activator: Register series viewer plug-in: Image Viewer
____________________________
Welcome to Apache Felix Gogo

telnetd is running on 127.0.0.1:17179
gosh: stopping shell
```

**Comment by leonardorame** [comment]
Yes, I didn't install Gnome, this is a pretty basic install, do you know which libraries I must install?, I don't want the whole Gnome Destkop.

**Comment by nroduit** [comment]
You should have a look [here](https://github.com/openjdk/jdk/tree/master/src/java.desktop/unix/native/libawt_xawt/xawt) (implementation of java.awt.Desktop).

**Comment by nroduit** [comment]
Please reopen this issue if it has not been resolved in the current version.
