### ISSUE TITLE
Weasis Dicom-web request

### ISSUE THREAD

**Issue by dentalbug** [nroduit/Weasis#432]
### Describe the bug. What happened?

Dear team,
i still report this isssue in my point of view as a bug.
Maybe i'm wrong i appologize to be mistaken.
Environment ist Windows 10, newset version, Orthanc pacs already installes.
Weasis 4.12 ist running well with Pacs Node and file loading.
Unfortunately do i have a problem using dicom-web command line.

start weasis://%24dicom%3Ars+-u+%22http%3A%2F%2Flocalhost%3A8042%2Fdicom-web%22+-r+%22patientID%3D2892%22

It seem like then web adress for the rest-api request changes during request ??

a.) org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost:8042/dicom-web/studie
b.)org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost/dicom-web/studies

i would really appreciate to get help in that case.

Kind regards
Alfred

### What version of Weasis are you running?

4.12

### On which system the problem occurs?

Windows

### Relevant log output

```shell
02.07.2023 20:51:32.056 *DEBUG* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost:8042/dicom-web/studies/1.2.276.0.7230010.3.1.2.1058451343.16140.1688245240.370/series?includefield=0008103E,00080060,0020000E,00200011,00081190
02.07.2023 20:51:32.099 *DEBUG* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost/dicom-web/studies/1.2.276.0.7230010.3.1.2.1058451343.16140.1688245240.370/series/1.2.276.0.7230010.3.1.3.1058451343.16140.1688245240.369/instances?includefield=00080018,00200013,00081190
02.07.2023 20:51:32.100 *WARN* [Dicom Model-pool-3-thread-1] org.weasis.core.api.util.NetworkUtil: http Status 404 - Not Found
02.07.2023 20:51:32.100 *TRACE* [Dicom Model-pool-3-thread-1] org.weasis.core.api.util.NetworkUtil: HttpURLConnection ERROR, server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"><HTML><HEAD><TITLE>Not Found</TITLE><META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD><BODY><h2>Not Found</h2><hr><p>HTTP Error 404. The requested resource is not found.</p></BODY></HTML>
02.07.2023 20:51:32.100 *ERROR* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS all instances with seriesUID 1.2.276.0.7230010.3.1.3.1058451343.16140.1688245240.369 org.weasis.core.util.StreamIOException: Not Found
	at org.weasis.core.api.util.NetworkUtil.readResponse(NetworkUtil.java:184)
	at org.weasis.core.api.util.NetworkUtil.prepareConnection(NetworkUtil.java:157)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:80)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:73)
	at org.weasis.dicom.explorer.rs.RsQueryResult.parseJSON(RsQueryResult.java:139)
	at org.weasis.dicom.explorer.rs.RsQueryResult.fillInstance(RsQueryResult.java:465)
	at org.weasis.dicom.explorer.rs.RsQueryResult.fillSeries(RsQueryResult.java:444)
	at org.weasis.dicom.explorer.rs.RsQueryResult.applyAllFilters(RsQueryResult.java:250)
	at org.weasis.dicom.explorer.rs.RsQueryResult.buildFromPatientID(RsQueryResult.java:128)
	at org.weasis.dicom.explorer.rs.RsQueryParams.fillPatientList(RsQueryParams.java:229)
	at org.weasis.dicom.explorer.rs.RsQueryParams.doInBackground(RsQueryParams.java:167)
	at org.weasis.dicom.explorer.rs.RsQueryParams.doInBackground(RsQueryParams.java:45)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
02.07.2023 20:51:32.100 *DEBUG* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost:8042/dicom-web/studies/1.2.276.0.7230010.3.1.2.1058451343.4764.1688245240.274/series?includefield=0008103E,00080060,0020000E,00200011,00081190
02.07.2023 20:51:32.135 *DEBUG* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost/dicom-web/studies/1.2.276.0.7230010.3.1.2.1058451343.4764.1688245240.274/series/1.2.276.0.7230010.3.1.3.1058451343.4764.1688245240.273/instances?includefield=00080018,00200013,00081190
02.07.2023 20:51:32.136 *WARN* [Dicom Model-pool-3-thread-1] org.weasis.core.api.util.NetworkUtil: http Status 404 - Not Found
02.07.2023 20:51:32.136 *TRACE* [Dicom Model-pool-3-thread-1] org.weasis.core.api.util.NetworkUtil: HttpURLConnection ERROR, server response: <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN""http://www.w3.org/TR/html4/strict.dtd"><HTML><HEAD><TITLE>Not Found</TITLE><META HTTP-EQUIV="Content-Type" Content="text/html; charset=us-ascii"></HEAD><BODY><h2>Not Found</h2><hr><p>HTTP Error 404. The requested resource is not found.</p></BODY></HTML>
02.07.2023 20:51:32.136 *ERROR* [Dicom Model-pool-3-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS all instances with seriesUID 1.2.276.0.7230010.3.1.3.1058451343.4764.1688245240.273 org.weasis.core.util.StreamIOException: Not Found
	at org.weasis.core.api.util.NetworkUtil.readResponse(NetworkUtil.java:184)
	at org.weasis.core.api.util.NetworkUtil.prepareConnection(NetworkUtil.java:157)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:80)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:73)
	at org.weasis.dicom.explorer.rs.RsQueryResult.parseJSON(RsQueryResult.java:139)
	at org.weasis.dicom.explorer.rs.RsQueryResult.fillInstance(RsQueryResult.java:465)
	at org.weasis.dicom.explorer.rs.RsQueryResult.fillSeries(RsQueryResult.java:444)
	at org.weasis.dicom.explorer.rs.RsQueryResult.applyAllFilters(RsQueryResult.java:250)
	at org.weasis.dicom.explorer.rs.RsQueryResult.buildFromPatientID(RsQueryResult.java:128)
	at org.weasis.dicom.explorer.rs.RsQueryParams.fillPatientList(RsQueryParams.java:229)
	at org.weasis.dicom.explorer.rs.RsQueryParams.doInBackground(RsQueryParams.java:167)
	at org.weasis.dicom.explorer.rs.RsQueryParams.doInBackground(RsQueryParams.java:45)
	at java.desktop/javax.swing.SwingWorker$1.call(Unknown Source)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.desktop/javax.swing.SwingWorker.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

**Comment by nroduit** [comment]
Already answered in  https://github.com/nroduit/Weasis/issues/264

The RetrieveURL value provided by Orthanc in response is wrong.
