### ISSUE TITLE
Weasis does not even reach the splash screen - possible wayland and flatpak interaction?  

### ISSUE THREAD

**Issue by unsafeunaudited** [nroduit/Weasis#449]
### Describe the bug. What happened?

Summary: The flatpak version does not open and does not even reach the splash/loading screen of Weasis.

I tried the 4.1.2 rpm installer from github and it runs without issue.

Of note, in the log below, it keeps showing X11 related errors (I am on wayland).

### What version of Weasis are you running?

4.1.2

### On which system the problem occurs?

Linux

### Relevant log output

```shell
WARNING: package com.sun.awt not in java.desktop
27.07.2023 08:56:32.826 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
27.07.2023 08:56:32.873 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
27.07.2023 08:56:32.894 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=host, weasis.name=Weasis, weasis.version=4.1.2, weasis.config.hash=-960773013, weasis.path=/home/host/.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/app/lib/app, weasis.pref.local.session=true, weasis.codebase.local=/app/lib/app, felix.extended.config.properties=file:/app/lib/app/conf/ext-config.properties, felix.config.properties=file:/app/lib/app/conf/config.properties, weasis.source.id=630703E9, weasis.profile=default, http.agent=Weasis/4.1.2 (Linux; 6.4.4-200.fc38.x86_64; amd64; pf:default; rv:4.1.2) Java/20.0.1}
27.07.2023 08:56:32.908 *INFO* [main] org.weasis.launcher.Singleton: Singleton server 630703E9 already running on port 41,221
27.07.2023 08:56:32.908 *INFO* [main] org.weasis.launcher.Singleton: Connect to 630703E9 on port 41,221
27.07.2023 08:56:32.915 *SEVERE* [main] org.weasis.launcher.Singleton: No server is running
java.net.ConnectException: Connection refused
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.Net.connect(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.connect(Unknown Source)
	at java.base/java.net.SocksSocketImpl.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.connect(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at java.base/java.net.Socket.<init>(Unknown Source)
	at org.weasis.launcher.Singleton.connectToServer(Singleton.java:170)
	at org.weasis.launcher.Singleton.invoke(Singleton.java:152)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:39)
27.07.2023 08:56:32.916 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 45,921
27.07.2023 08:56:32.920 *INFO* [main] org.weasis.launcher.Singleton: Remove file with same prefix 630703E9_41221
27.07.2023 08:56:32.924 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
27.07.2023 08:56:32.925 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
27.07.2023 08:56:32.935 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.linux.windows.decoration = false
27.07.2023 08:56:32.974 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = null
27.07.2023 08:56:33.071 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Cannot register the main frame
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
	at java.desktop/java.awt.Window.<init>(Unknown Source)
	at java.desktop/java.awt.Frame.<init>(Unknown Source)
	at java.desktop/java.awt.Frame.<init>(Unknown Source)
	at java.desktop/javax.swing.JFrame.<init>(Unknown Source)
	at org.weasis.launcher.WeasisLauncher.lambda$loadProperties$12(WeasisLauncher.java:894)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
27.07.2023 08:56:33.096 *SEVERE* [main] org.weasis.launcher.WeasisLoader: Display splashscreen
java.lang.reflect.InvocationTargetException
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at java.desktop/java.awt.EventQueue.invokeAndWait(Unknown Source)
	at org.weasis.launcher.WeasisLoader.open(WeasisLoader.java:165)
	at org.weasis.launcher.WeasisLauncher.loadProperties(WeasisLauncher.java:974)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:179)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:42)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.GraphicsEnvironment.checkHeadless(Unknown Source)
	at java.desktop/java.awt.Window.init(Unknown Source)
	at java.desktop/java.awt.Window.<init>(Unknown Source)
	at java.desktop/java.awt.Window.<init>(Unknown Source)
	at org.weasis.launcher.WeasisLoader.initGUI(WeasisLoader.java:72)
	at org.weasis.launcher.WeasisLoader.lambda$open$3(WeasisLoader.java:168)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
27.07.2023 08:56:33.098 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
27.07.2023 08:56:33.098 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
27.07.2023 08:56:33.098 *INFO* [main] org.weasis.launcher.WeasisLauncher: Clean plug-in cache because Weasis has crashed during the previous launch
27.07.2023 08:56:33.118 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 4.1.2
  Current version = 4.1.2
  Application name = Weasis
  Application Source ID = 630703E9
  Application Profile = default
  Application local codebase = /app/lib/app
  Application codebase URL = file:/app/lib/app
  Application configuration file = file:/app/lib/app/conf/config.properties
  Application extension configuration file = file:/app/lib/app/conf/ext-config.properties
  User = host
  User home directory = /home/host/.weasis
  Resources path = /app/lib/app/resources
  Preferences directory = /home/host/.weasis/preferences/host/default
  Look and Feel = org.weasis.launcher.FlatWeasisTheme
  Languages path = file:/app/lib/app/bundle-i18n/
  Languages available = en,ar,bg_BG,bs_BA,cs,de,el,es,fa,fr,hr_HR,hu_HU,it,ja,ko,ms_MY,pl_PL,pt,pt_BR,ro,ru_RU,si,sk_SK,sr_RS,sv,ta_IN,tr,uk,vi,vi_VN,zh_CN,zh-Hans,zh_TW
  OSGI native specs = linux-x86-64
  HTTP user agent = Weasis/4.1.2 (Linux; 6.4.4-200.fc38.x86_64; amd64; pf:default; rv:4.1.2) Java/20.0.1
  Operating system = Linux 6.4.4-200.fc38.x86_64 amd64
  Java vendor = Eclipse Adoptium
  Java version = 20.0.1
  Java Path = /app/lib/runtime
  Java max memory (less survivor space) = 1.8 GiB
***** End of Configuration *****
27.07.2023 08:56:33.119 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

27.07.2023 08:56:35.184 *INFO* [FelixStartLevel] org.apache.sling.commons.log.internal.LogManager: LogManager: Logging set up from context
ERROR: Bundle weasis-core [22] Error starting file:/app/lib/app/bundle/weasis-core-4.1.2.jar (org.osgi.framework.BundleException: Activator start error in bundle weasis-core [22].)
java.lang.ExceptionInInitializerError
	at org.weasis.core.ui.editor.image.dockable.MeasureTool.<clinit>(MeasureTool.java:80)
	at org.weasis.core.internal.Activator.start(Activator.java:74)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Unknown Source)
Caused by: java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/sun.awt.HeadlessToolkit.getBestCursorSize(Unknown Source)
	at org.weasis.core.api.gui.util.Feature.getCursor(Feature.java:181)
	at org.weasis.core.api.gui.util.Feature.getSvgCursor(Feature.java:167)
	at org.weasis.core.api.gui.util.ActionW.<clinit>(ActionW.java:49)
	... 8 more
ERROR: Bundle weasis-base-ui [31] Error starting file:/app/lib/app/bundle/weasis-base-ui-4.1.2.jar (org.osgi.framework.BundleException: Activator start error in bundle weasis-core [22].)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:491)
	at org.apache.felix.framework.BundleContextImpl.getProperty(BundleContextImpl.java:66)
	at org.weasis.core.api.service.WProperties.getProperty(WProperties.java:50)
	at org.weasis.core.internal.StreamBackingStoreImpl.<init>(StreamBackingStoreImpl.java:65)
	at org.weasis.core.internal.Activator.start(Activator.java:54)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:1006)
	at org.apache.felix.framework.BundleImpl.start(BundleImpl.java:992)
	at org.weasis.base.ui.internal.Activator.start(Activator.java:39)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Unknown Source)
ERROR: Bundle weasis-dicom-viewer2d [7] Error starting file:/app/lib/app/bundle/weasis-dicom-viewer2d-4.1.2.jar (org.osgi.framework.BundleException: Activator start error in bundle weasis-dicom-viewer2d [7].)
java.lang.IllegalStateException: Invalid BundleContext.
	at org.apache.felix.framework.BundleContextImpl.checkValidity(BundleContextImpl.java:491)
	at org.apache.felix.framework.BundleContextImpl.getProperty(BundleContextImpl.java:66)
	at org.weasis.core.api.service.WProperties.getProperty(WProperties.java:50)
	at org.weasis.core.api.service.WProperties.getIntProperty(WProperties.java:96)
	at org.weasis.core.ui.editor.image.MouseActions.<init>(MouseActions.java:42)
	at org.weasis.core.ui.editor.image.ImageViewerEventManager.<init>(ImageViewerEventManager.java:66)
	at org.weasis.dicom.viewer2d.EventManager.<init>(EventManager.java:154)
	at org.weasis.dicom.viewer2d.EventManager.getInstance(EventManager.java:148)
	at org.weasis.dicom.viewer2d.internal.Activator.start(Activator.java:60)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Unknown Source)
27.07.2023 08:56:35.539 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Cannot not start framework.
java.awt.HeadlessException: 
No X11 DISPLAY variable was set,
or no headful library support was found,
but this program performed an operation which requires it,

	at java.desktop/java.awt.Desktop.getDesktop(Unknown Source)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:253)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:42)
27.07.2023 08:56:35.539 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Weasis cache will be cleaned at next launch.
27.07.2023 08:56:35.539 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: State of the framework:
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.framework-7.0.5 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-databind-2.14.2 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-2.4.0 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-send-4.1.2 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.scr-2.2.6 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer3d-4.1.2 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-linux-x86-64-2.4.0 RESOLVED
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer2d-4.1.2 RESOLVED
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.command-1.1.2 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.configadmin-1.9.26 ACTIVE
27.07.2023 08:56:35.540 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jaxb-osgi-3.0.2 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-viewer2d-4.1.2 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-img-4.6.1 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-core-2.14.2 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-au-4.1.2 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-opencv-core-linux-x86-64-4.6.1.dcm RESOLVED
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * osgi.promise-8.1.0.202212101352 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-explorer-4.1.2 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * docking-frames-1.1.4 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.shell-1.1.4 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.bundlerepository-2.0.10 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.metatype-1.2.4 ACTIVE
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-4.1.2 RESOLVED
27.07.2023 08:56:35.541 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-imageio-codec-4.1.2 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-isowriter-4.1.2 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.glassfish.jakarta.json-1.1.5 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.swing-11.0.0 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-sr-4.1.2 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-qr-4.1.2 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-codec-4.1.2 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.runtime-1.1.6 ACTIVE
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-ui-4.1.2 RESOLVED
27.07.2023 08:56:35.542 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.prefs-1.1.0 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-wave-4.1.2 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-rt-4.1.2 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.joml-1.10.5 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-annotations-2.14.2 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.sling.commons.log-3.0.2.r5 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.core-11.0.0 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * slf4j.api-1.7.36 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * net.lingala.zip4j-2.11.4 ACTIVE
27.07.2023 08:56:35.543 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.osgi.service.component-1.5.1.202212101352 ACTIVE
```

### Additional contextual elements

Affected OS: Fedora 38 Workstation, Fedora Silverblue 38 (GNOME 44.3)
Type of installer: flatpak
Windowing system: wayland

**Comment by nroduit** [comment]
The application is launched as if there were no desktop installed. However, Wayland is included in the [configuration](https://github.com/flathub/io.github.nroduit.Weasis/blob/master/io.github.nroduit.Weasis.yaml#L10).

This may be related to [this problem](https://www.reddit.com/r/pop_os/comments/10kybky/no_x11_display_variable_was_set_when_using/). We'll see if the next release of Java 21 fixes this.

**Comment by ispanos** [comment]
I have the same issue on Fedora 38 Workstation. However this is just a one-time use of weasis and I can do what I need using Xorg.

**Comment by nroduit** [comment]
I tested just after installing Fedora 38 and the result of the different Weasis installers with the default configuration (Wayland) is: 
- Flatpak, Weasis doesn't launch. This confirms the bug described above, which seems to exist for all Java applications with a JDK higher than 17.
- Package RPM => = OK
- SNAP => = OK

**Comment by nroduit** [comment]
As the X11 fallback seems buggy, the workaround with Flatpak is:

- run `flatpak run --socket=x11 --nosocket=wayland io.github.nroduit.Weasis`

or 

- Install Flatseal: `flatpak install flathub com.github.tchx84.Flatseal`
- Set Wayland to OFF
![image](https://github.com/nroduit/Weasis/assets/993975/15a2039d-a0fa-41ca-b47d-05fc06e462f0)

**Comment by nroduit** [comment]
Add a reference to the issue on the download page.

**Comment by AlbertoFabbri93** [comment]
I am having this issue on OpenSuse Aeon with flatpak and wayland. The app does not even show the splash screen.

The workaround with Flatseal works though.

**Comment by G10h4ck** [comment]
> * flatpak run --socket=x11 --nosocket=wayland io.github.nroduit.Weasis

had this problem too, this workaround worked for me

**Comment by robertvazan** [comment]
I think you should configure it with `--socket=x11` until the underlying issue is fixed.

**Comment by Loreton** [comment]
had this problem too on ubuntu22.04, 
`run flatpak run --socket=x11 --nosocket=wayland io.github.nroduit.Weasis`
workaround worked for me
