### ISSUE TITLE
Filesystem folder with umlauts causes java.nio.file.InvalidPathException

### ISSUE THREAD

**Issue by akohlbecker** [nroduit/Weasis#468]
### Describe the bug. What happened?

1. Start Weasis
2. Open with the filebrowser that contains a file or folder with at least one umlaut (e.g. ü) in the filename (File > Open > DICOM > Local device)
3. The fiel dialog seems fozen and the log reports below error

### What version of Weasis are you running?

4.2.0 flatpack

### On which system the problem occurs?

Linux

### Relevant log output

```shell
18.09.2023 21:54:04.136 *INFO* [AWT-EventQueue-0] org.weasis.dicom.qr.DicomQrFactory: DICOM Q/R is activated
Exception in thread "Basic L&F File Loading Thread" java.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /home/user/H??fte
        at java.base/sun.nio.fs.UnixPath.encode(Unknown Source)
        at java.base/sun.nio.fs.UnixPath.<init>(Unknown Source)
        at java.base/sun.nio.fs.UnixFileSystem.getPath(Unknown Source)
        at java.base/java.nio.file.Path.of(Unknown Source)
        at java.base/java.nio.file.Paths.get(Unknown Source)
        at java.desktop/sun.awt.shell.ShellFolder.getShellFolder(Unknown Source)
        at java.desktop/javax.swing.filechooser.FileSystemView.getFiles(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run0(Unknown Source)
        at java.desktop/javax.swing.plaf.basic.BasicDirectoryModel$FilesLoader.run(Unknown Source)
        at java.base/java.lang.Thread.run(Unknown Source)
```

### Additional contextual elements

In the example above the folder `/home/user/Hüfte` was causing the problem.

**Comment by nroduit** [comment]
Which Linux distribution is it? Because this is the first time I've seen an encoding problem on a Linux desktop.

Weasis assumes that the file system is encoded in UTF8 for Linux. Is this the case? you can check with the command 
``` bash
env | grep LANG=
```
Should return: LANG=xxx.UTF-8 (e.g. LANG=fr_CH.UTF-8)

**Comment by akohlbecker** [comment]
This is KDE neon 5.27

The `LANG` variable has the value `LANG=en_US.UTF-8`

Interestingly the Weasis log contains the following warning:
~~~
(process:2): Gtk-WARNING **: 08:06:21.236: Locale not supported by C library.
~~~

The full locale settings are 

~~~
$ locale                                                                                                      
LANG=en_US.UTF-8
LANGUAGE=
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=de_DE.UTF-8
LC_TIME=de_DE.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=de_DE.UTF-8
LC_MESSAGES=POSIX
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT=de_DE.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
~~~

**Comment by nroduit** [comment]
I don't know if it's related to Flatpak or the system, but there's a Locale configuration problem. It seems necessary to reconfigure it.

The LANGUAGE field should not be empty and there are mixed locales, see https://github.com/flatpak/flatpak/issues/3712

**Comment by akohlbecker** [comment]
I am using mixed locales by purpose and would only change this for testing this issue. First of all I installed the deb package of weasis and with this installation I can no longer reproduce this problem. So it is obviously caused by flatpacks inability to handle mixed locales. 
I may do further testing, but as this is not a bug in weasis I suggest to close this ticket.
Thanks a lot for your help.
