### ISSUE TITLE
how can i add third part dependencies to weasis?

### ISSUE THREAD

**Issue by a347807131** [nroduit/Weasis#473]
### Describe the bug. What happened?

i wanted to use okhttp for http request in weasis , but ClassNotFoundException occured when i was lunching app after adding the dependency in pom.

thanks to any help;

### What version of Weasis are you running?

4.2.0

### On which system the problem occurs?

Windows

### Relevant log output

```shell
C:\Users\Gatsby\scoop\apps\openjdk21\21-35\bin\java.exe -Xms64m -Xmx768m -Dgosh.port=17179 --enable-preview "-javaagent:C:\Users\Gatsby\AppData\Local\Programs\IntelliJ IDEA Ultimate\lib\idea_rt.jar=60219:C:\Users\Gatsby\AppData\Local\Programs\IntelliJ IDEA Ultimate\bin" -Dfile.encoding=UTF-8 -Dsun.stdout.encoding=UTF-8 -Dsun.stderr.encoding=UTF-8 -classpath D:\IdeaProjects\Weasis\weasis-launcher\target\classes;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.framework\7.0.5\org.apache.felix.framework-7.0.5.jar;C:\Users\Gatsby\.m2\repository\org\codehaus\mojo\animal-sniffer-annotations\1.9\animal-sniffer-annotations-1.9.jar;C:\Users\Gatsby\.m2\repository\com\formdev\flatlaf\3.2\flatlaf-3.2.jar;C:\Users\Gatsby\.m2\repository\com\formdev\flatlaf-intellij-themes\3.2\flatlaf-intellij-themes-3.2.jar;C:\Users\Gatsby\.m2\repository\com\formdev\flatlaf-extras\3.2\flatlaf-extras-3.2.jar;C:\Users\Gatsby\.m2\repository\com\github\weisj\jsvg\1.0.0\jsvg-1.0.0.jar;C:\Users\Gatsby\.m2\repository\org\tukaani\xz\1.9\xz-1.9.jar;C:\Users\Gatsby\.m2\repository\org\apache\sling\org.apache.sling.commons.log\3.0.2-r5\org.apache.sling.commons.log-3.0.2-r5.jar;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.metatype\1.2.4\org.apache.felix.metatype-1.2.4.jar;C:\Users\Gatsby\.m2\repository\net\sf\kxml\kxml2\2.2.2\kxml2-2.2.2.jar;C:\Users\Gatsby\.m2\repository\xmlpull\xmlpull\1.1.3.1\xmlpull-1.1.3.1.jar;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.scr\2.2.6\org.apache.felix.scr-2.2.6.jar;C:\Users\Gatsby\.m2\repository\org\osgi\osgi.promise\8.1.0\osgi.promise-8.1.0.jar;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.bundlerepository\2.0.10\org.apache.felix.bundlerepository-2.0.10.jar;C:\Users\Gatsby\.m2\repository\org\easymock\easymock\3.4\easymock-3.4.jar;C:\Users\Gatsby\.m2\repository\org\objenesis\objenesis\2.2\objenesis-2.2.jar;C:\Users\Gatsby\.m2\repository\org\joml\joml\1.10.5\joml-1.10.5.jar;C:\Users\Gatsby\.m2\repository\com\fasterxml\jackson\core\jackson-databind\2.15.1\jackson-databind-2.15.1.jar;C:\Users\Gatsby\.m2\repository\com\fasterxml\jackson\core\jackson-annotations\2.15.1\jackson-annotations-2.15.1.jar;C:\Users\Gatsby\.m2\repository\com\fasterxml\jackson\core\jackson-core\2.15.1\jackson-core-2.15.1.jar;C:\Users\Gatsby\.m2\repository\org\slf4j\slf4j-api\1.7.36\slf4j-api-1.7.36.jar;C:\Users\Gatsby\.m2\repository\com\miglayout\miglayout-swing\11.0\miglayout-swing-11.0.jar;C:\Users\Gatsby\.m2\repository\com\miglayout\miglayout-core\11.0\miglayout-core-11.0.jar;C:\Users\Gatsby\.m2\repository\org\weasis\core\weasis-core-img\4.8.0\weasis-core-img-4.8.0-jdk11.jar;C:\Users\Gatsby\.m2\repository\org\osgi\osgi.core\8.0.0\osgi.core-8.0.0.jar;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.configadmin\1.9.26\org.apache.felix.configadmin-1.9.26.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.service.component\1.5.1\org.osgi.service.component-1.5.1.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.namespace.extender\1.0.1\org.osgi.namespace.extender-1.0.1.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.util.function\1.0.0\org.osgi.util.function-1.0.0.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.util.promise\1.0.0\org.osgi.util.promise-1.0.0.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.service.component.annotations\1.5.1\org.osgi.service.component.annotations-1.5.1.jar;C:\Users\Gatsby\.m2\repository\org\osgi\osgi.annotation\8.1.0\osgi.annotation-8.1.0.jar;C:\Users\Gatsby\.m2\repository\org\apache\felix\org.apache.felix.prefs\1.1.0\org.apache.felix.prefs-1.1.0.jar;C:\Users\Gatsby\.m2\repository\org\osgi\org.osgi.service.prefs\1.1.1\org.osgi.service.prefs-1.1.1.jar org.weasis.launcher.AppLauncher dicom:get -l D:\IdeaProjects\vtk-mpr\DRData
13.10.2023 15:31:09.037 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
13.10.2023 15:31:09.083 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
13.10.2023 15:31:09.083 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = dicom:get
13.10.2023 15:31:09.083 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 1 = -l
13.10.2023 15:31:09.083 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 2 = D:\IdeaProjects\vtk-mpr\DRData
13.10.2023 15:31:09.102 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=Gatsby, weasis.name=Weasis, weasis.version=4.2.1-SNAPSHOT, weasis.config.hash=174745, weasis.path=C:\Users\Gatsby\.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/D:/IdeaProjects/Weasis/weasis-launcher/target, weasis.pref.local.session=true, weasis.codebase.local=D:\IdeaProjects\Weasis\weasis-launcher\target, felix.config.properties=file:/D:/IdeaProjects/Weasis/weasis-launcher/target/conf/base.json, weasis.source.id=36B3A9D5, weasis.profile=default, http.agent=Weasis/ (Windows 10; 10.0; amd64; pf:default; rv:4.2.1-SNAPSHOT) Java/21}
13.10.2023 15:31:09.131 *INFO* [main] org.weasis.launcher.Singleton: Singleton server 36B3A9D5 already running on port 60,134
13.10.2023 15:31:09.131 *INFO* [main] org.weasis.launcher.Singleton: Connect to 36B3A9D5 on port 60,134
13.10.2023 15:31:09.132 *SEVERE* [main] org.weasis.launcher.Singleton: No server is running
java.net.ConnectException: Connection refused: connect
	at java.base/sun.nio.ch.Net.connect0(Native Method)
	at java.base/sun.nio.ch.Net.connect(Net.java:589)
	at java.base/sun.nio.ch.Net.connect(Net.java:578)
	at java.base/sun.nio.ch.NioSocketImpl.connect(NioSocketImpl.java:583)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:327)
	at java.base/java.net.Socket.connect(Socket.java:751)
	at java.base/java.net.Socket.connect(Socket.java:686)
	at java.base/java.net.Socket.<init>(Socket.java:555)
	at java.base/java.net.Socket.<init>(Socket.java:324)
	at org.weasis.launcher.Singleton.connectToServer(Singleton.java:170)
	at org.weasis.launcher.Singleton.invoke(Singleton.java:152)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:39)
13.10.2023 15:31:09.135 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 60,222
13.10.2023 15:31:09.139 *INFO* [main] org.weasis.launcher.Singleton: Remove file with same prefix 36B3A9D5_60134
13.10.2023 15:31:09.157 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = zh_CN
13.10.2023 15:31:09.157 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = en_US
13.10.2023 15:31:09.157 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
13.10.2023 15:31:09.157 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
13.10.2023 15:31:09.158 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
13.10.2023 15:31:09.158 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
13.10.2023 15:31:09.158 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
13.10.2023 15:31:09.158 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
13.10.2023 15:31:09.272 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = -1
13.10.2023 15:31:09.883 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = false
13.10.2023 15:31:09.883 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = false
13.10.2023 15:31:09.883 *INFO* [main] org.weasis.launcher.WeasisLauncher: Clean plug-in cache because Weasis has crashed during the previous launch
13.10.2023 15:31:09.906 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = 4.2.1-SNAPSHOT
  Current version = 4.2.1-SNAPSHOT
  Application name = Weasis
  Application Source ID = 36B3A9D5
  Application Profile = default
  Application local codebase = D:\IdeaProjects\Weasis\weasis-launcher\target
  Application codebase URL = file:/D:/IdeaProjects/Weasis/weasis-launcher/target
  Application configuration file = file:/D:/IdeaProjects/Weasis/weasis-launcher/target/conf/base.json
  User = Gatsby
  User home directory = C:\Users\Gatsby\.weasis
  Resources path = D:\IdeaProjects\Weasis\weasis-distributions\resources
  Preferences directory = C:\Users\Gatsby\.weasis\preferences\Gatsby\default
  Look and Feel = com.formdev.flatlaf.FlatDarculaLaf
  Languages available = en
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/ (Windows 10; 10.0; amd64; pf:default; rv:4.2.1-SNAPSHOT) Java/21
  Operating system = Windows 10 10.0 amd64
  Java vendor = Oracle Corporation
  Java version = 21
  Java Path = C:\Users\Gatsby\scoop\apps\openjdk21\21-35
  Java max memory (less survivor space) = 768.0 MiB
***** End of Configuration *****
13.10.2023 15:31:09.908 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

13.10.2023 15:31:11.552 *INFO* [FelixStartLevel] org.apache.sling.commons.log.internal.LogManager: LogManager: Logging set up from context
13.10.2023 15:31:12.102 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
13.10.2023 15:31:12.103 *INFO* [FelixStartLevel] org.weasis.core.internal.cv.NativeOpenCVCodec: Native OpenCV is activated
13.10.2023 15:31:12.104 *INFO* [FelixStartLevel] org.weasis.core.internal.Activator: Register Image Codec Plug-in: OpenCV imgcodecs
13.10.2023 15:31:12.113 *INFO* [FelixStartLevel] org.weasis.core.internal.Activator: Register Image Codec Plug-in: JDK ImageIO
13.10.2023 15:31:12.120 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Activate DicomCodec
13.10.2023 15:31:12.124 *INFO* [FelixStartLevel] org.weasis.core.internal.Activator: Register Image Codec Plug-in: dcm4che
ERROR: Bundle weasis-base-ui [30] Error starting file:C:/Users/Gatsby/.m2/repository/org/weasis/base/weasis-base-ui/4.2.1-SNAPSHOT/weasis-base-ui-4.2.1-SNAPSHOT.jar (org.osgi.framework.BundleException: Activator start error in bundle weasis-base-ui [30].)
java.lang.NoClassDefFoundError: okhttp3/OkHttp
	at org.weasis.core.ui.util.RisHttpApiUtils.validateLicence(RisHttpApiUtils.java:55)
	at org.apache.felix.framework.util.SecureAction.startActivator(SecureAction.java:849)
	at org.apache.felix.framework.Felix.activateBundle(Felix.java:2429)
	at org.apache.felix.framework.Felix.startBundle(Felix.java:2335)
	at org.apache.felix.framework.Felix.setActiveStartLevel(Felix.java:1566)
	at org.apache.felix.framework.FrameworkStartLevelImpl.run(FrameworkStartLevelImpl.java:297)
	at java.base/java.lang.Thread.run(Thread.java:1583)
Caused by: java.lang.ClassNotFoundException: okhttp3.OkHttp not found by weasis-core [18]
	at org.apache.felix.framework.BundleWiringImpl.findClassOrResourceByDelegation(BundleWiringImpl.java:1591)
	at org.apache.felix.framework.BundleWiringImpl.access$300(BundleWiringImpl.java:79)
	at org.apache.felix.framework.BundleWiringImpl$BundleClassLoader.loadClass(BundleWiringImpl.java:1976)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 10 more
13.10.2023 15:31:12.594 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: SR => org.weasis.dicom.sr.SRElementFactory
13.10.2023 15:31:12.612 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: AU => org.weasis.dicom.au.AuElementFactory
13.10.2023 15:31:12.625 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: ECG => org.weasis.dicom.wave.WaveElementFactory
13.10.2023 15:31:12.625 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: HD => org.weasis.dicom.wave.WaveElementFactory
13.10.2023 15:31:12.729 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: RTSTRUCT => org.weasis.dicom.rt.RTElementFactory
13.10.2023 15:31:12.729 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: RTPLAN => org.weasis.dicom.rt.RTElementFactory
13.10.2023 15:31:12.729 *INFO* [FelixStartLevel] org.weasis.dicom.codec.DicomCodec: Register DicomSpecialElementFactory: RTDOSE => org.weasis.dicom.rt.RTElementFactory
13.10.2023 15:31:12.777 *INFO* [FelixStartLevel] org.weasis.dicom.viewer3d.View3DFactory: 3D Viewer is activated
13.10.2023 15:31:12.893 *INFO* [JOGL-GLWorkerThread-] org.weasis.dicom.viewer3d.View3DFactory: Checking 3D capabilities
13.10.2023 15:31:12.935 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: Default System Application
13.10.2023 15:31:12.935 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: 2D Viewer
13.10.2023 15:31:12.935 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: Orthogonal MPR
13.10.2023 15:31:12.935 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: DICOM Structured Report
13.10.2023 15:31:12.937 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: DICOM Voice Audio Waveform
13.10.2023 15:31:12.937 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: DICOM Waveform
13.10.2023 15:31:12.939 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: Image Viewer
13.10.2023 15:31:12.940 *INFO* [AWT-EventQueue-0] org.weasis.dicom.rt.RtDisplayToolFactory: Activate the RT panel
13.10.2023 15:31:14.262 *INFO* [JOGL-GLWorkerThread-] org.weasis.dicom.viewer3d.View3DFactory: *PERF* 3D initialization time: 1369 ms
13.10.2023 15:31:14.263 *INFO* [JOGL-GLWorkerThread-] org.weasis.dicom.viewer3d.View3DFactory: Video card for OpenGL: NVIDIA Corporation, Quadro GP100/PCIe/SSE2 4.6 (Core profile, arb, compat[ES2, ES3, ES31, ES32], FBO, hardware) - 4.6.0 NVIDIA 528.33
13.10.2023 15:31:14.263 *INFO* [AWT-EventQueue-0] org.weasis.core.internal.Activator: Register series viewer plug-in: 3D Viewer
13.10.2023 15:31:14.279 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Cannot not start framework.
java.lang.IllegalStateException: Main User Interface bundle cannot be started
	at org.weasis.launcher.WeasisLauncher.checkBundleUI(WeasisLauncher.java:322)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:279)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:42)
13.10.2023 15:31:14.279 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Weasis cache will be cleaned at next launch.
13.10.2023 15:31:14.280 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: State of the framework:
13.10.2023 15:31:14.280 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.framework-7.0.5 ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-viewer2d-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-databind-2.15.1 ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-isowriter-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-2.4.0 ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-rt-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-au-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.scr-2.2.6 ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-explorer-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-imageio-codec-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-send-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer3d-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.command-1.1.2 ACTIVE
13.10.2023 15:31:14.281 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.configadmin-1.9.26 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-windows-x86-64-2.4.0 RESOLVED
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jaxb-osgi-3.0.2 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer2d-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-core-2.15.1 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * osgi.promise-8.1.0.202212101352 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * docking-frames-1.1.6 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-sr-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.shell-1.1.4 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.bundlerepository-2.0.10 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.metatype-1.2.4 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.glassfish.jakarta.json-1.1.5 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.swing-11.0.0 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.runtime-1.1.6 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.prefs-1.1.0 ACTIVE
13.10.2023 15:31:14.282 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.joml-1.10.5 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-ui-4.2.1.SNAPSHOT RESOLVED
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-img-4.8.0 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-annotations-2.15.1 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-codec-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-opencv-core-windows-x86-64-4.8.0.dcm RESOLVED
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.sling.commons.log-3.0.2.r5 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-qr-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.core-11.0.0 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * slf4j.api-1.7.36 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-wave-4.2.1.SNAPSHOT ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * net.lingala.zip4j-2.11.4 ACTIVE
13.10.2023 15:31:14.283 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.osgi.service.component-1.5.1.202212101352 ACTIVE

Process finished with exit code -1
```

**Comment by nroduit** [comment]
I can provide assistance within the scope of the Weasis project, but not to issues outside that scope with other objectives.
Unfortunately, I can't respond to all requests. My priority is to support open-source developments that contribute to the common effort to improve Weasis.

This problem isn't a bug, but rather a misconfiguration of dependencies according to OSGI principles. However, I don't see the point of adding a new http client if there isn't an obvious reason, [HTTPClient](https://www.baeldung.com/java-9-http-client) should be sufficient.

**Comment by a347807131** [comment]
thanks for reply anyway.

**Comment by a347807131** [comment]
ignore the specified dependency, what configuration detailed in pom.xml and base.json should i do if i want to import a third jar dependency in weasis.  I almost got insane by the question. @nroduit 
Thanks for any reply.

**Comment by nroduit** [comment]
There are several examples in Weasis of third-party libraries that are embedded in a jar or loaded directly into the plugin list.
In both cases, the import and export java packages required by OSGI must be defined (in MANIFEST.MF of jar), as each plugin is isolated in memory by default.
