### ISSUE TITLE
Weasis 3.8.1 with DCM4CHEE 5 Archive Dockerized

### ISSUE THREAD

**Issue by DagonsaIT** [nroduit/Weasis#496]
### Describe the bug. What happened?

It seems that when i try to deploy weasis.war from the JBoss CLI or Wildfly Web Console it throws an error, all the dependencies and files are in the .war 
But the viewer in particular it doesn't deploy.  Throwing the error in the image.

![image](https://github.com/nroduit/Weasis/assets/25586669/a0783c60-bd1c-453d-b00b-aea98d8075d6)

### What version of Weasis are you running?

3.8.1

### On which system the problem occurs?

Linux

### Relevant log output

```shell
{"WFLYCTL0080: Failed services" => {"jboss.deployment.unit.\"weasis.war\".undertow-deployment.UndertowDeploymentInfoService" => "Failed to start service
    Caused by: java.lang.IllegalArgumentException: UT010011: Filter UrlRewriteFilter of type class org.tuckey.web.filters.urlrewrite.UrlRewriteFilter does not implement jakarta.servlet.Filter"}}
```

### Additional contextual elements

I builded dcm4chee with the docker-compose.yml. Not manually. Re-opening from the Issue #71

**Comment by nroduit** [comment]
Read this [recommentation](https://groups.google.com/g/dcm4che/c/L-OnKaLXV-o/m/BaKj-V2uEAAJ)

**Comment by SePro3** [comment]
Hello Nicolas, thanks for the rapid respond. 
I used that recommendation that you give, but when i want to see an image its says that i need an app to open it. This can be the problem of the https and the valid certificate? 
Thank you very much.

**Comment by nroduit** [comment]
To help the discussion, and as there are many ways to integrate Weasis, it's necessary to first outline the objectives you're trying to achieve. Then, what documentation you are following to make this integration?

**Comment by SePro3** [comment]
Hello Nicolas, good morning for you. 
I could integrate it, the only thing that was missing was to download the native version (duh), but now i incounter the problem that when i want to view an image from Web, it opens Weasis but no the image. I read the documentation from the page, i don't see whats missing.

**Comment by nroduit** [comment]
Most of the time, you will find the response by [activating the rolling log files](https://weasis.org/en/tutorials/logging/).

**Comment by SePro3** [comment]
Thanks Nicolas, i activated logging and found this error:

`3.11.2023 09:57:41.668 *ERROR* [Dicom Model-pool-2-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS with PatientID 22142304^^^DCM4CHEE.DBA7828C.0A00698B org.weasis.core.util.StreamIOException: Not Found
	at org.weasis.core.api.util.NetworkUtil.readResponse(NetworkUtil.java:184)
	at org.weasis.core.api.util.NetworkUtil.prepareConnection(NetworkUtil.java:157)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:80)
	at org.weasis.core.api.util.NetworkUtil.getHttpResponse(NetworkUtil.java:73)
	at org.weasis.dicom.explorer.rs.RsQueryResult.parseJSON(RsQueryResult.java:140)`

I don't particulary deduce what it can be with my minimum knowledge of Java, what it doesn't found specifically? The image i can see it if i import it by DICOM Retrieve with the AET. Thank you

**Comment by nroduit** [comment]
Provide the full log file in debug level to understand what the query is.

**Comment by SePro3** [comment]
Here is it.

[default.log](https://github.com/nroduit/Weasis/files/13452423/default.log)

**Comment by nroduit** [comment]
You have a 404 error because the URL of the service is not valid.

> 23.11.2023 09:57:41.653 *DEBUG* [Dicom Model-pool-2-thread-1] org.weasis.dicom.explorer.rs.RsQueryResult: QIDO-RS request: http://localhost:8080/dcm4chee-arc/ui2//dcm4chee-arc/aets/DCM4CHEE/rs/studies?00100020=22142304&00100021=DCM4CHEE.DBA7828C.0A00698B&includefield=00080020,00080030,00080050,00080061,00080090,00081030,00100010,00100020,00100021,00100030,00100040,0020000D,00200010&includedefaults=false
23.11.2023 09:57:41.668 *WARN* [Dicom Model-pool-2-thread-1] org.weasis.core.api.util.NetworkUtil: http Status 404 - Not Found

**Comment by SePro3** [comment]
Yes, i have changed to remove a **/**, but it throws the same http status. I have to use the http url because i can't have a valid certificate, we are testing it. So, what url can i put? Or i'm failing on the propierties of the RESTful services?

**Comment by nroduit** [comment]
404 means that the resource does not exist. You must enter the correct URL. That's why I'm asking which documentation you follow.
The URL must start with: http://localhost:8080/dcm4chee-arc/aets/DCM4CHEE/rs/studies

**Comment by nroduit** [comment]
We're closing this issue due to inactivity over the past several months. If the problem persists or if you have any further information to provide, please feel free to reopen this issue or create a new one.
We appreciate your contributions and feedback!
