### ISSUE TITLE
Error: Unable to print the image (File > Print > DICOM Print)

### ISSUE THREAD

**Issue by engenhariahtr** [nroduit/Weasis#548]
### Describe the bug. What happened?

Portuguese: Olá, estou enviando uma impressão via DICOM e não está funcionando gera o seguinte erro: Error -> "Unable to print the image", a configuração do AE title, Hostname e porta está certa, inclusive consegue ser feito ping ao destino, mas não imprime. No controlador Printlink5 que envia para a DRY873 está tudo funcionando normalmente.

English: Hello, I'm sending a print to DICOM and it's not working, it generates the following error: Error -> "Unable to print the image", the configuration of the AE title, Hostname and port is correct, the destination can even be ping, but it cannot prints. In the Printlink5 controller that sends to the DRY873, everything is working normally.

### What version of Weasis are you running?

4.3.0

### On which system the problem occurs?

Windows

### Relevant log output

```shell
Last running version = 4.3.0
  Current version = 4.3.0
  Application name = Weasis Dicomizer
  Application Source ID = 9E1396C0
  Application Profile = dicomizer
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/base.json
  Application extension configuration file = file:/C:/Program%20Files/Weasis/app/conf/dicomizer.json
  User = souzadp
  User home directory = C:\Users\souzadp\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\souzadp\.weasis\preferences\souzadp\dicomizer
  Look and Feel = com.formdev.flatlaf.FlatIntelliJLaf
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = en,bg_BG,bs_BA,ca_ES,cs,de,el,es,fa,fa_IR,fr,hr_HR,hu_HU,it,ja,ko,pl_PL,pt,pt_BR,ro,ru_RU,si,sr_RS,sv,tr,uk,vi,vi_VN,zh_CN,zh_Hans,zh_TW
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/4.3.0 (Windows 10; 10.0; amd64; pf:dicomizer; rv:4.3.0) Java/21.0.2
  Operating system = Windows 10 10.0 amd64
  Java vendor = Eclipse Adoptium
  Java version = 21.0.2
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 1.9 GiB
***** End of Configuration *****
25.04.2024 10:26:13.829 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

25.04.2024 10:26:14.993 *INFO* [FelixStartLevel] org.opencv.osgi: Successfully loaded OpenCV native library.
25.04.2024 10:26:16.474 *SEVERE* [AWT-EventQueue-0] org.weasis.launcher.WeasisLauncher: Init command session
java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.weasis.launcher.WeasisLauncher.initCommandSession(WeasisLauncher.java:592)
	at org.weasis.launcher.WeasisLauncher.lambda$executeCommands$4(WeasisLauncher.java:378)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
Caused by: java.net.BindException: Address already in use: bind
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.Net.bind(Unknown Source)
	at java.base/sun.nio.ch.NioSocketImpl.bind(Unknown Source)
	at java.base/java.net.ServerSocket.bind(Unknown Source)
	at java.base/java.net.ServerSocket.<init>(Unknown Source)
	at org.apache.felix.gogo.shell.Telnet.start(Telnet.java:118)
	at org.apache.felix.gogo.shell.Telnet.telnetd(Telnet.java:81)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.apache.felix.gogo.runtime.Reflective.invoke(Reflective.java:143)
	at org.apache.felix.gogo.runtime.CommandProxy.execute(CommandProxy.java:91)
	at org.apache.felix.gogo.runtime.Closure.executeCmd(Closure.java:599)
	at org.apache.felix.gogo.runtime.Closure.executeStatement(Closure.java:526)
	at org.apache.felix.gogo.runtime.Closure.execute(Closure.java:415)
	at org.apache.felix.gogo.runtime.Pipe.doCall(Pipe.java:416)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:229)
	at org.apache.felix.gogo.runtime.Pipe.call(Pipe.java:59)
	at java.base/java.util.concurrent.FutureTask.run(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.base/java.lang.Thread.run(Unknown Source)
```

### Additional contextual elements

![config Dicom Node _para impressão](https://github.com/nroduit/Weasis/assets/168114658/11ec37a4-817c-4638-877e-0f3d4bba82a4)
![error](https://github.com/nroduit/Weasis/assets/168114658/29e6771c-ae47-458d-a227-e1e787198f84)

**Comment by nroduit** [comment]
Please provide the DICOM negotiation [logs](https://weasis.org/en/tutorials/logging/), as the above log corresponds to the Dicomizer launch.
See also https://github.com/nroduit/Weasis/discussions/382

**Comment by engenhariahtr** [comment]
I'm sendo the log.

[default.log](https://github.com/nroduit/Weasis/files/15149612/default.log)

**Comment by nroduit** [comment]
According to the logs, the printer cannot be reached with the defined IP and port. So I don't see a problem, but rather a misconfiguration or access restrictions to the printer.

**Comment by engenhariahtr** [comment]
I didn't see any configuration errors, could you tell me more specifically what could be configured to solve the problem?

I'm increment the configuration of the DICOM PRINT .xml || dicomPrinterNodes.xml >>>
<?xml version="1.0" encoding="UTF-8"?>
-<nodes>
<node dpi="DPI_100" printOnlySelectedView="false" showingAnnotations="true" emptyDensity="BLACK" trim="NO" borderDensity="BLACK" smoothingType="MEDIUM" magnificationType="REPLICATE" imageDisplayFormat="STANDARD\1,1" filmSizeId="IN10X12" filmOrientation="PORTRAIT" colorPrint="false" numberOfCopies="1" filmDestination="MAGAZINE" priority="LOW" mediumType="BLUE FILM" port="6000" hostname="177.22.63.177" aeTitle="DRY873-2" tsuid="NONE" usageType="" type="PRINTER" description="DRY873-2_PRINTER"/>
</nodes>

**Comment by nroduit** [comment]
Have you tried to reach the printer from your workstation with a command?
Powershell: `Test-NetConnection -ComputerName 177.22.63.177 -Port 6000`
