### ISSUE TITLE
exception occurred when launching weasis?

### ISSUE THREAD

**Issue by a347807131** [nroduit/Weasis#574]
### Describe the bug. What happened?

The program can't run correctly after installed through msi package in win10 x64 system.

### What version of Weasis are you running?

4.3.0

### On which system the problem occurs?

Windows

### Relevant log output

```shell
24.07.2024 13:03:24.420 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
24.07.2024 13:03:24.485 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
24.07.2024 13:03:24.500 *INFO* [main] org.weasis.launcher.ConfigData: Properties: {weasis.user=Gatsby, weasis.name=Weasis, weasis.version=4.3.0, weasis.config.hash=174372, weasis.path=C:\Users\Gatsby\.weasis, weasis.launch.type=NATIVE, weasis.codebase.url=file:/C:/Program%20Files/Weasis/app, weasis.pref.local.session=true, weasis.codebase.local=C:\Program Files\Weasis\app, felix.config.properties=file:/C:/Program%20Files/Weasis/app/conf/base.json, weasis.source.id=64D59807, weasis.profile=default, http.agent=Weasis/4.3.0 (Windows 10; 10.0; amd64; pf:default; rv:4.3.0) Java/21}
24.07.2024 13:03:24.530 *INFO* [main] org.weasis.launcher.Singleton: Local port of the Singleton server: 64,162
24.07.2024 13:03:24.550 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
24.07.2024 13:03:24.550 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
24.07.2024 13:03:24.550 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
24.07.2024 13:03:24.550 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
24.07.2024 13:03:24.551 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
24.07.2024 13:03:24.551 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
24.07.2024 13:03:24.551 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 5
24.07.2024 13:03:24.551 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
24.07.2024 13:03:24.641 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of flatlaf.uiScale = 
24.07.2024 13:03:25.069 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
24.07.2024 13:03:25.069 *INFO* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
24.07.2024 13:03:25.099 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = null
  Current version = 4.3.0
  Application name = Weasis
  Application Source ID = 64D59807
  Application Profile = default
  Application local codebase = C:\Program Files\Weasis\app
  Application codebase URL = file:/C:/Program%20Files/Weasis/app
  Application configuration file = file:/C:/Program%20Files/Weasis/app/conf/base.json
  User = Gatsby
  User home directory = C:\Users\Gatsby\.weasis
  Resources path = C:\Program Files\Weasis\app\resources
  Preferences directory = C:\Users\Gatsby\.weasis\preferences\Gatsby\default
  Look and Feel = org.weasis.launcher.FlatWeasisTheme
  Languages path = file:/C:/Program%20Files/Weasis/app/bundle-i18n/
  Languages available = en,ar,bg_BG,bqi,bs_BA,cs,de,el,es,fa,fr,hr_HR,hu_HU,it,ja,ko,ms_MY,pl_PL,pt,pt_BR,ro,ru_RU,si,sk_SK,sr_RS,sv,ta_IN,tr,uk,vi,vi_VN,zh_CN,zh-Hans,zh_TW
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/4.3.0 (Windows 10; 10.0; amd64; pf:default; rv:4.3.0) Java/21
  Operating system = Windows 10 10.0 amd64
  Java vendor = Oracle Corporation
  Java version = 21
  Java Path = C:\Program Files\Weasis\runtime
  Java max memory (less survivor space) = 4.0 GiB
***** End of Configuration *****
24.07.2024 13:03:25.100 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

24.07.2024 13:03:27.805 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Cannot not start framework.
java.lang.IllegalStateException: Main User Interface bundle cannot be started
	at org.weasis.launcher.WeasisLauncher.checkBundleUI(WeasisLauncher.java:320)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:277)
	at org.weasis.launcher.AppLauncher.main(AppLauncher.java:43)
24.07.2024 13:03:27.806 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Weasis cache will be cleaned at next launch.
24.07.2024 13:03:27.806 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: State of the framework:
24.07.2024 13:03:27.807 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.framework-7.0.5 ACTIVE
24.07.2024 13:03:27.807 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-windows-x86-64-2.5.0 RESOLVED
24.07.2024 13:03:27.807 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-databind-2.15.1 ACTIVE
24.07.2024 13:03:27.807 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-send-4.3.0 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer3d-4.3.0 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.scr-2.2.6 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-viewer2d-4.3.0 RESOLVED
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.command-1.1.2 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.configadmin-1.9.26 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-viewer2d-4.3.0 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-core-2.15.1 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-au-4.3.0 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-img-4.8.1.1 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * osgi.promise-8.1.0.202212101352 ACTIVE
24.07.2024 13:03:27.808 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-explorer-4.3.0 RESOLVED
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jogamp-2.5.0 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * docking-frames-1.1.6 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.shell-1.1.4 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.bundlerepository-2.0.10 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.metatype-1.2.4 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-core-4.3.0 RESOLVED
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-imageio-codec-4.3.0 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-isowriter-4.3.0 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.swing-11.0.0 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-opencv-core-windows-x86-64-4.8.1.dcm RESOLVED
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-qr-4.3.0 ACTIVE
24.07.2024 13:03:27.809 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-sr-4.3.0 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-codec-4.3.0 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.gogo.runtime-1.1.6 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-ui-4.3.0 RESOLVED
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.prefs-1.1.0 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-wave-4.3.0 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-dicom-rt-4.3.0 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.joml-1.10.5 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.fasterxml.jackson.core.jackson-annotations-2.15.1 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.sling.commons.log-3.0.2.r5 ACTIVE
24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * com.miglayout.core-11.0.0 ACTIVE
24.07.2024 13:03:27.811 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * slf4j.api-1.7.36 ACTIVE
24.07.2024 13:03:27.811 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * jaxb-osgi-4.0.3 ACTIVE
24.07.2024 13:03:27.811 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * net.lingala.zip4j-2.11.5 ACTIVE
24.07.2024 13:03:27.811 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.osgi.service.component-1.5.1.202212101352 ACTIVE
```

**Comment by nroduit** [comment]
> 24.07.2024 13:03:27.810 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * weasis-base-ui-4.3.0 RESOLVED

This means that the main UI module cannot be started. In this case, the cache is cleared at the next startup. Does the application work on the next startup?

Note that if you have made changes to modules and kept the same version number, then the bundle cache will be corrupted. See the warning box in [the documentation](https://weasis.org/en/getting-started/building-weasis).

**Comment by arunjoshtech** [comment]
For past one week I am facing issues, three different user asked support, while launch weasis from browser it close the browser, Tried with Chrome, edge. and worked with Firefox for one user and next day and it also get closed. Later installed older version like 3.8 and working fine.
kindly look into it

**Comment by nroduit** [comment]
@arunjoshtech It looks like you've reported an issue that's not related to the original topic. To keep the conversation organized and ensure your question gets the right attention, could you please start a new issue with a description that allows the problem to be reproduced?  

> For past one week I am facing issues, three different user asked support, while launch weasis from browser it close the browser, Tried with Chrome, edge. and worked with Firefox for one user and next day it also get closed. Later installed older version like 3.8 and working fine. kindly look into it
