### ISSUE TITLE
Crashes on launch with "org.weasis.launcher.FileUtil: Cannot install bundle docking-frames-1.1.2" in the boot log

### ISSUE THREAD

**Issue by wesnolte** [nroduit/Weasis#609]
### Describe the bug. What happened?

I've recently been to the doc and they gave me a CD to view images. But the app crashes immediately following the splash screen. I'm starting the app using viewer-win32.exe

### What version of Weasis are you running?

3.5.3

### On which system the problem occurs?

Windows

### Relevant log output

```shell
21.11.2024 16:32:59.655 *INFO* [main] org.weasis.launcher.ConfigData: Starting Weasis...
21.11.2024 16:32:59.682 *INFO* [main] org.weasis.launcher.ConfigData: Initialization of the launch configuration...
21.11.2024 16:32:59.683 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 0 = $dicom:get
21.11.2024 16:32:59.683 *INFO* [main] org.weasis.launcher.ConfigData: Main arg 1 = --portable
21.11.2024 16:32:59.687 *INFO* [main] org.weasis.launcher.ConfigData: Starting portable version
21.11.2024 16:32:59.697 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.lang.code = en
21.11.2024 16:32:59.697 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of locale.format.code = system
21.11.2024 16:32:59.698 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.level = INFO
21.11.2024 16:32:59.698 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.activate = false
21.11.2024 16:32:59.698 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.number = 5
21.11.2024 16:32:59.698 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.file.size = 10MB
21.11.2024 16:32:59.698 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.stack.limit = 3
21.11.2024 16:32:59.699 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of org.apache.sling.commons.log.pattern = {0,date,dd.MM.yyyy HH:mm:ss.SSS} *{4}* [{2}] {3}: {5}
21.11.2024 16:33:00.278 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.disclaimer = true
21.11.2024 16:33:00.278 *CONFIG* [main] org.weasis.launcher.WeasisLauncher: Config of weasis.show.release = true
21.11.2024 16:33:00.288 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
***** Configuration *****
  Last running version = null
  Current version = 3.5.3
  Application name = Weasis
  Application Source ID = 08ABA319
  Application Profile = default
  Application local codebase = C:\prycd\weasis
  Application codebase URL = file:/C:/prycd/weasis
  Application configuration file = file:/C:/prycd/weasis/conf/config.properties
  Application extension configuration file = file:/C:/prycd/weasis/conf/ext-config.properties
  User = ###
  User home directory = C:\Users\###\.weasis
  Resources path = C:\prycd\weasis\resources
  Preferences directory = C:\Users\###\.weasis\preferences\wwnol\default
  Look and Feel = org.pushingpixels.substance.api.skin.SubstanceTwilightLookAndFeel
  Languages path = file:/C:/prycd/weasis/bundle-i18n/buildNumber.properties
  Languages available = en,ar,bs_BA,bg_BG,zh_CN,zh_TW,hr_HR,cs,fr,de,el,hu_HU,it,ja,ko,ms_MY,pl_PL,pt,pt_BR,ro,ru_RU,sr_RS,sk_SK,es,sv,tr,uk,vi,vi_VN
  OSGI native specs = windows-x86-64
  HTTP user agent = Weasis/3.5.3 (Windows 11; 10.0; amd64)
  Operating system = Windows 11 10.0 amd64
  Java vendor = Oracle Corporation
  Java version = 17.0.11
  Java Path = C:\Program Files\Java\jdk-17
  Java max memory (less survivor space) = 768.0 MiB
***** End of Configuration *****
21.11.2024 16:33:00.290 *INFO* [main] org.weasis.launcher.WeasisLauncher: 
Starting OSGI Bundles...

         | | /| / /__ ___ ____ (_)__
         | |/ |/ / -_) _ `(_-</ (_-<
         |__/|__/\__/\_,_/___/_/___/

21.11.2024 16:33:00.410 *SEVERE* [main] org.weasis.launcher.FileUtil: Cannot install bundle docking-frames-1.1.2
org.osgi.framework.BundleException: Could not create bundle object.
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3312)
	at org.apache.felix.framework.BundleContextImpl.installBundle(BundleContextImpl.java:147)
	at org.weasis.launcher.AutoProcessor.installBundle(AutoProcessor.java:532)
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:348)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:105)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:250)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:223)
	at org.weasis.launcher.WeasisLauncher.main(WeasisLauncher.java:181)
Caused by: java.io.FileNotFoundException: META-INF/MANIFEST.MF
	at org.apache.felix.framework.util.Util.getMultiReleaseAwareManifestHeaders(Util.java:996)
	at org.apache.felix.framework.BundleImpl.createRevision(BundleImpl.java:1266)
	at org.apache.felix.framework.BundleImpl.<init>(BundleImpl.java:113)
	at org.apache.felix.framework.Felix.installBundle(Felix.java:3260)
	... 7 more
21.11.2024 16:33:00.410 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Cannot not start framework.
java.lang.IllegalStateException: A bundle cannot be started
	at org.weasis.launcher.AutoProcessor.processAutoProperties(AutoProcessor.java:361)
	at org.weasis.launcher.AutoProcessor.process(AutoProcessor.java:105)
	at org.weasis.launcher.WeasisLoader.setFelix(WeasisLoader.java:250)
	at org.weasis.launcher.WeasisLauncher.launch(WeasisLauncher.java:223)
	at org.weasis.launcher.WeasisLauncher.main(WeasisLauncher.java:181)
21.11.2024 16:33:00.411 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: Weasis cache will be cleaned at next launch.
21.11.2024 16:33:00.411 *SEVERE* [main] org.weasis.launcher.WeasisLauncher: State of the framework:
21.11.2024 16:33:00.411 *SEVERE* [main] org.weasis.launcher.WeasisLauncher:  * org.apache.felix.framework-6.0.3 STARTING
```

### Additional contextual elements

- The app is installed by a bat file supplied on DVD.
- Windows 11 Home N version 22H2 OS Build 22621.4387

**Comment by wesnolte** [comment]
I was able to download the most recent version of weasis and open the DICOM (whatever that is). I can see the images. My guess is that the executable packaged on the supplied DVD only works for 32-bit machines whereas mine is 64-bit. 

So, my bad. You can close this.
